deployment:
  image: quay.io/go-skynet/local-ai:latest
  env:
    threads: 14
    contextSize: 512
    modelsPath: "/models"

# Optionally create a PVC, mount the PV to the LocalAI Deployment,
# and download a model to prepopulate the models directory
modelsVolume:
  enabled: true
  url: "https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin"
  pvc:
    size: 8Gi
    accessModes:
    - ReadWriteOnce
  auth:
    # Optional value for HTTP basic access authentication header
    basic: "" # 'username:password' base64 encoded

modelsTemplate:
  name: "ggml-gpt4all-j-v1.3-groovy.bin.tmpl"
  url: "https://raw.githubusercontent.com/brianhammons/LocalAI/master/prompt-templates/ggml-gpt4all-j.tmpl"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"